name: test github var in run cmd

on:
  push:
    branches:
      - var-in-run

jobs:
  test:
    name: test var in run
    runs-on: ubuntu-latest
    steps:
      - name: test echo
        run: |
          echo "${{ format('refs/heads/{0}', github.event.repository.default_branch) }}"
